name: puma
channels:
  - conda-forge
dependencies:
  - python

  # pumapy
  - numpy =1.21.2 
  - scikit-image =0.18.3
  - scipy =1.7.1
  - matplotlib =3.4.3
  - pyevtk =1.4.1
  - pyvista

  # puma cpp
  - fftw
  - eigen
  - openmp
  - cmake >=3.11.0 # needed >=3.11.0

  # puma gui
  - qt >=5.9.0 # needed >=5.9.0

  # texgen
  - swig

  # nice to have
  - pip
  - cython
  - scikit-umfpack
  - jupyterlab
  - ipyvtklink
  - ipympl
